---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./workflow-test

patches:
  # Patch oci resources to use rc images
  - path: oci-repository-patch.yaml

  # Patch Flux kustomizations with environment-related fields
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      version: v1
    path: flux-kustomization-patch.yaml
