---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./workflow-test

patches:
  # Patch oci resources to use rc images
  - path: oci-patch.yaml
  # - target:
  #     kind: OCIRepository
  #   patch: |-
  #     - op: add
  #       path: /spec/ref
  #       value:
  #         semver: ">=0.0.0"
  #         semverFilter: ".*-rc.*"
