apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: workflow-test
  namespace: hriv
spec:
  values:
    image:
      tag: 0.0.0 # {"$imagepolicy": "hriv:workflow-test-stable:tag"}
