---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: workflow-test

configMapGenerator:
  - name: release-name
    literals:
      - RELEASE_NAME=workflow-test

patches:
  - path: helm-values-patch.yaml
  # - target:
  #     kind: OCIRepository
  #   patch: |-
  #     - op: replace
  #       path: /spec/url
  #       value: oci://ghcr.io/bcit-tlu/charts/workflow-test
  # - target:
  #     kind: Kustomization
  #   patch: |-
  #     - op: replace
  #       path: /spec/path
  #       value: latest
