---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # - vault-static-secrets.yaml

namespace: workflow-test

configMapGenerator:
  - name: release-name
    literals:
      - RELEASE_NAME=workflow-test
    options:
      disableNameSuffixHash: true

patches:
  - path: helm-values-patch.yaml
