apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - hriv-images.yaml

patches:
  - path: patch-frontend.yaml
  - path: patch-backend.yaml
  - path: patch-backup.yaml
