apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-kustomization.yaml
  - helm-release.yaml
  # - image-auto-update.yaml
  - namespace.yaml
  - oci-repository.yaml
  - vault-auth.yaml

# Teach kustomize how to update generated names
configurations:
  - kustomizeconfig.yaml
