# Watches `oci/{chartName}` registries for new versions
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ${RELEASE_NAME}
spec:
  interval: 48h
  url: oci://ghcr.io/bcit-ltc/charts/${RELEASE_NAME}
  ref:
    semver: ">= 1.0.0"
